inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-packaging
  - rubocop-performance
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRailsVersion: 7.0
  TargetRubyVersion: 3.0
  Exclude:
    - .git/**/*
    - .github/**/*
    - bin/**/*
    - gemfiles/**/*
    - node_modules/**/*
    - tmp/**/*
    - vendor/**/*

Layout/LineLength:
  Enabled: false

Lint/MissingSuper:
  Exclude:
    - 'spec/**/*'

Metrics/AbcSize:
  Exclude:
    - 'spec/**/*'

Metrics/BlockLength:
  Exclude:
    - 'chrono_model.gemspec'
    - 'spec/**/*'

Metrics/MethodLength:
  Exclude:
    - 'spec/**/*'

Naming/MethodName:
  AllowedPatterns:
    - '_INSERT_'
    - '_UPDATE_'
    - '_DELETE_'

Naming/PredicateName:
  Enabled: false

Rails/ApplicationRecord:
  Enabled: false

Rails/Date:
  Enabled: false

Rails/FilePath:
  Enabled: false

Rails/RakeEnvironment:
  Enabled: false

Rails/SkipsModelValidations:
  AllowedMethods: ['touch', 'touch_all', 'update_column', 'update_columns']

Rails/TimeZone:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/SpecFilePathFormat:
  Enabled: false

Style/ArgumentsForwarding:
  Enabled: false

Style/GlobalVars:
  Exclude:
    - 'spec/**/*'

# NOTE: This cop is enabled by RuboCop Rails, because active support adds this
# method to hash, but `except` is not available in specs
Style/HashExcept:
  Exclude:
    - 'spec/**/*'

Style/IfUnlessModifier:
  Enabled: false
