inherit_from: .rubocop_todo.yml

require:
  - rubocop-packaging
  - rubocop-performance
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRailsVersion: 5.0
  TargetRubyVersion: 2.2
  Exclude:
    - 'gemfiles/**/*'
    - 'lib/**/*'
    - 'vendor/bundle/**/*'
    - 'tmp/**/*'

Gemspec/DevelopmentDependencies:
  Enabled: false

Layout/LineLength:
  Max: 140
  Exclude:
    - 'spec/**/*'

Metrics/AbcSize:
  Exclude:
    - 'spec/**/*'

Metrics/BlockLength:
  Exclude:
    - 'chrono_model.gemspec'
    - 'spec/**/*'

Metrics/MethodLength:
  Exclude:
    - 'spec/**/*'

Rails/ApplicationRecord:
  Enabled: false

Rails/Date:
  Enabled: false

Rails/RakeEnvironment:
  Enabled: false

Rails/SkipsModelValidations:
  AllowedMethods: ['touch', 'touch_all', 'update_column', 'update_columns']

Rails/TimeZone:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

Style/GlobalVars:
  Exclude:
    - 'spec/**/*'

Style/HashExcept:
  Enabled: false
