name: Legacy Ruby specs

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  test:
    name: Legacy Ruby specs
    runs-on: ubuntu-20.04

    services:
      db:
        image: postgres:12
        ports: ['5432:5432']
        env:
          POSTGRES_HOST_AUTH_METHOD: trust

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    strategy:
      matrix:
        ruby-version: ['2.2', '2.3', '2.4', '2.5']
        gemfile: [rails_5.0, rails_5.1, rails_5.2, rails_6.0]

        exclude:
          - ruby-version: '2.2'
            gemfile: rails_6.0
          - ruby-version: '2.2'
            gemfile: rails_6.1
          - ruby-version: '2.2'
            gemfile: rails_7.0
          - ruby-version: '2.3'
            gemfile: rails_6.0
          - ruby-version: '2.3'
            gemfile: rails_6.1
          - ruby-version: '2.3'
            gemfile: rails_7.0
          - ruby-version: '2.4'
            gemfile: rails_6.0
          - ruby-version: '2.4'
            gemfile: rails_6.1
          - ruby-version: '2.4'
            gemfile: rails_7.0
          - ruby-version: '2.5'
            gemfile: rails_7.0

    env:
      BUNDLE_GEMFILE: gemfiles/${{ matrix.gemfile }}.gemfile
      TEST_CONFIG: ./spec/config.github.yml

    steps:
    - uses: actions/checkout@v3
    - name: Set up Database
      run: |
        psql -c "CREATE ROLE runner SUPERUSER LOGIN CREATEDB;" -U postgres -h localhost
        psql -c "CREATE DATABASE chronomodel;" -U postgres -h localhost
        psql -c "CREATE DATABASE chronomodel_railsapp;" -U postgres -h localhost
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    - name: Run specs and publish code coverage
      uses: paambaati/codeclimate-action@v3.2.0
      env:
        CC_TEST_REPORTER_ID: dedfb7472ee410eec459bff3681d9a8fd8dd237e9bd7e8675a7c8eb7e253bba9
      with:
        coverageCommand: bundle exec rake
